"""Domain models for query classification, entity linking, and retrieval planning."""

from enum import Enum
from typing import Any
from pydantic import BaseModel, Field
from app.models.entities import EntityType


class QueryIntent(str, Enum):
    """Categorical classification of user query intent."""

    DIRECT_FACT = "DIRECT_FACT"          # Simple lookup of specific factual detail
    ENTITY_LOOKUP = "ENTITY_LOOKUP"      # Summarize or describe a specific entity
    RELATIONSHIP = "RELATIONSHIP"        # Determine connection between two known entities
    MULTI_HOP = "MULTI_HOP"              # Infer indirect relations through intermediary entities
    GLOBAL = "GLOBAL"                    # Dataset-wide thematic or holistic inquiry
    COMPARISON = "COMPARISON"            # Compare two products, versions, or customers
    NO_ANSWER = "NO_ANSWER"              # Query outside domain scope or unverifiable


class RetrievalStrategy(str, Enum):
    """Candidate retrieval strategies available in GraphRAGX."""

    VECTOR = "vector"
    GRAPH = "graph"
    HYBRID = "hybrid"
    MULTI_HOP = "multi_hop"
    GLOBAL = "global"


class LinkedEntity(BaseModel):
    """An entity mention detected in a user query and linked to knowledge graph nodes."""

    raw_mention: str = Field(..., description="Surface string as it appeared in the query")
    canonical_id: str = Field(..., description="Matched canonical entity ID")
    canonical_name: str = Field(..., description="Canonical display name")
    entity_type: EntityType = Field(default=EntityType.OTHER, description="Inferred entity type")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Linking confidence")


class RetrievalPlan(BaseModel):
    """Execution plan generated by query analysis to guide retrieval engines."""

    query: str = Field(..., description="Original user query")
    intent: QueryIntent = Field(default=QueryIntent.DIRECT_FACT, description="Classified intent")
    strategy: RetrievalStrategy = Field(default=RetrievalStrategy.HYBRID, description="Selected strategy")
    seed_entities: list[LinkedEntity] = Field(default_factory=list, description="Extracted anchor entities")
    target_entity_types: list[EntityType] = Field(default_factory=list, description="Target entity types sought")
    max_hops: int = Field(default=2, ge=1, le=5, description="Maximum traversal depth for graph search")
    require_paths: bool = Field(default=False, description="Whether explicit graph paths are required for reasoning")
    top_k: int = Field(default=5, ge=1, description="Number of top chunks desired")
    filters: dict[str, Any] = Field(default_factory=dict, description="Metadata constraints (version, department)")
